version: '3.7'

services:
  eth.blockchain.io:
    container_name: eth.blockchain.io
    image: trufflesuite/ganache-cli
    command: --accounts 50 --blockTime 1 > acctKeys.json 2>&1

  # contract bootstrapper
  hbmpc.coordinator.io:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ./configs/hbmpc.coordinator.io.toml:/root/.coordinator/config.toml
      - ./public-data:/root/.coordinator/public
      - ./contract.rl:/root/.coordinator/contract.rl
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - eth.blockchain.io
    command: ["./apps/sdk/wait-for-it.sh", "eth.blockchain.io:8545", "--", "python", "apps/sdk/coordinator.py"]

  hbmpc.peer0.io:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ./configs/hbmpc.peer0.io.toml:/root/.hbmpc/config.toml
      - ./public-data:/root/.hbmpc/public
      - ./contract.rl:/root/.hbmpc/contract.rl
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    command: ["./apps/sdk/wait-for-it.sh", "eth.blockchain.io:8545", "--", "python", "apps/robohash/server.py"]

  hbmpc.peer1.io:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ./configs/hbmpc.peer1.io.toml:/root/.hbmpc/config.toml
      - ./public-data:/root/.hbmpc/public
      - ./contract.rl:/root/.hbmpc/contract.rl
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    command: ["./apps/sdk/wait-for-it.sh", "eth.blockchain.io:8545", "--", "python", "apps/robohash/server.py"]

  hbmpc.peer2.io:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ./configs/hbmpc.peer2.io.toml:/root/.hbmpc/config.toml
      - ./public-data:/root/.hbmpc/public
      - ./contract.rl:/root/.hbmpc/contract.rl
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    command: ["./apps/sdk/wait-for-it.sh", "eth.blockchain.io:8545", "--", "python", "apps/robohash/server.py"]

  hbmpc.peer3.io:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ./configs/hbmpc.peer3.io.toml:/root/.hbmpc/config.toml
      - ./public-data:/root/.hbmpc/public
      - ./contract.rl:/root/.hbmpc/contract.rl
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    command: ["./apps/sdk/wait-for-it.sh", "eth.blockchain.io:8545", "--", "python", "apps/robohash/server.py"]

  eth.robohash.org:
    image: honeybadgermpc-local
    build:
        context: ../..
        dockerfile: Dockerfile
    volumes:
      - ./configs/hbmpc.client.io.toml:/root/.hbmpc/config.toml
      - ./contract.rl:/root/.hbmpc/contract.rl
      - ./public-data:/root/.hbmpc/public
      - ../../apps:/usr/src/HoneyBadgerMPC/apps
      - ../../honeybadgermpc:/usr/src/HoneyBadgerMPC/honeybadgermpc
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    depends_on:
      - hbmpc.peer0.io
      - hbmpc.peer1.io
      - hbmpc.peer2.io
      - hbmpc.peer3.io
    command: ["./apps/sdk/wait-for-it.sh", "hbmpc.peer3.io:8080", "--", "python", "apps/robohash/client.py", "--config-file", "~/.hbmpc/config.toml"]
